export type SuperModule = {
  slug: string;
  name: string;
  eyebrow: string;
  description: string;
  accent: "green" | "blue" | "amber" | "violet";
  features: string[];
  metrics: { label: string; value: string; detail: string }[];
  actions: string[];
};

export const superModules: SuperModule[] = [
  { slug:"intelligence", name:"Farm intelligence", eyebrow:"AI & DECISIONS", description:"Explainable crop, livestock and market guidance grounded in farm records.", accent:"violet", features:["Crop advisor","Soil analysis","Pest detection","Yield prediction","Selling windows","Farm assistant"], metrics:[{label:"Active advisories",value:"7",detail:"2 need review"},{label:"Model confidence",value:"73%",detail:"Rules baseline v1"},{label:"Prevented risk",value:"₹38K",detail:"Estimated this season"}], actions:["Ask farm assistant","Review predictions","Record outcome"] },
  { slug:"techniques", name:"Farming techniques", eyebrow:"KNOWLEDGE", description:"Practical playbooks for crops, animals, protected cultivation and regenerative farming.", accent:"green", features:["Crop guides","Precision farming","Hydroponics","Organic methods","Drip irrigation","Polyculture"], metrics:[{label:"Farm guides",value:"128",detail:"12 local languages"},{label:"Saved guides",value:"14",detail:"Available offline"},{label:"Completion",value:"62%",detail:"Learning plan"}], actions:["Browse guides","Save offline","Create farm playbook"] },
  { slug:"maintenance", name:"Maintenance & logs", eyebrow:"FIELD OPERATIONS", description:"Daily work, equipment care, irrigation schedules and inspection checklists.", accent:"amber", features:["Daily logs","Equipment service","Irrigation schedule","Inspections","Labour roster","Offline drafts"], metrics:[{label:"Due today",value:"9",detail:"3 high priority"},{label:"Equipment uptime",value:"96%",detail:"Across 18 assets"},{label:"Drafts",value:"2",detail:"Waiting to sync"}], actions:["Log activity","Create checklist","Schedule service"] },
  { slug:"analytics", name:"Analytics & reports", eyebrow:"PERFORMANCE", description:"Yield, cost, benchmark and seasonal trends across every enterprise.", accent:"blue", features:["Yield analytics","Cost analysis","Farm benchmarks","Satellite view","Season trends","Exports"], metrics:[{label:"Production value",value:"₹18.4L",detail:"+12.8% YoY"},{label:"Operating margin",value:"44%",detail:"+3.1 points"},{label:"Reports",value:"24",detail:"6 scheduled"}], actions:["Open analytics","Compare farms","Export report"] },
  { slug:"planning", name:"Production planning", eyebrow:"SEASONS & CAPACITY", description:"Coordinate calendars, people, inputs, harvests and multi-season forecasts.", accent:"green", features:["Crop calendar","Resource allocation","Labour planning","Harvest schedule","Season forecast","Input planning"], metrics:[{label:"Active cycles",value:"18",detail:"Across 7 farms"},{label:"Next harvest",value:"4 days",detail:"Butterhead lettuce"},{label:"Capacity used",value:"81%",detail:"Current season"}], actions:["Plan a cycle","Allocate inputs","View calendar"] },
  { slug:"logistics", name:"Logistics & supply", eyebrow:"FARM TO MARKET", description:"Coordinate buyers, transport, grading, cold storage and traceable delivery.", accent:"blue", features:["Buyer network","Mandi prices","Cold storage","Transport booking","Quality grading","Track & trace"], metrics:[{label:"In transit",value:"12",detail:"3 arriving today"},{label:"Cold capacity",value:"68%",detail:"42 MT available"},{label:"On-time delivery",value:"94%",detail:"Last 30 days"}], actions:["Book transport","Reserve storage","Track shipment"] },
  { slug:"finance", name:"Money & finance", eyebrow:"FARM ECONOMICS", description:"Understand profitability, schemes, insurance, credit and cooperative billing.", accent:"amber", features:["Farm P&L","Scheme finder","Microloans","Crop insurance","Input credit","FPO billing"], metrics:[{label:"Net cash flow",value:"₹2.8L",detail:"This quarter"},{label:"Receivables",value:"₹86K",detail:"5 invoices"},{label:"Eligible schemes",value:"6",detail:"Maharashtra"}], actions:["View P&L","Find schemes","Create invoice"] },
  { slug:"weather", name:"Weather & climate", eyebrow:"HYPERLOCAL", description:"Forecasts and crop-specific warnings translated into clear farm actions.", accent:"blue", features:["14-day forecast","Rain alerts","Frost warning","Crop advisory","Spray window","Climate history"], metrics:[{label:"Now",value:"27°C",detail:"Feels like 29°"},{label:"Rain chance",value:"68%",detail:"After 16:00"},{label:"Spray window",value:"2 hr",detail:"Before noon"}], actions:["View forecast","Set alert","Open crop advisory"] },
  { slug:"marketplace", name:"Agri marketplace", eyebrow:"BUY & SELL", description:"Inputs, produce, equipment rentals and trusted direct trade with INR checkout.", accent:"green", features:["Seeds & inputs","Produce sales","Equipment rental","Subscriptions","Escrow-ready payments","Order tracking"], metrics:[{label:"Orders",value:"28",detail:"This month"},{label:"Sales",value:"₹1.42L",detail:"+16% month on month"},{label:"Products",value:"34",detail:"29 in stock"}], actions:["Browse market","List product","Track orders"] },
  { slug:"community", name:"Community & guidance", eyebrow:"LEARN TOGETHER", description:"Trusted conversations connecting farmers, experts and local institutions.", accent:"violet", features:["Expert Q&A","Farmer forums","Video learning","KVK directory","Extension linkage","Local groups"], metrics:[{label:"Open questions",value:"42",detail:"Median reply 18 min"},{label:"Local experts",value:"16",detail:"Verified profiles"},{label:"Learning groups",value:"8",detail:"Near your farms"}], actions:["Ask an expert","Join discussion","Find a KVK"] },
  { slug:"news", name:"Agri news & alerts", eyebrow:"TRUSTED UPDATES", description:"Curated mandi, policy, outbreak, export and subsidy information—clearly sourced.", accent:"amber", features:["Mandi prices","Policy updates","Pest outbreaks","Trade news","Subsidies","Editorial review"], metrics:[{label:"New today",value:"18",detail:"All sources reviewed"},{label:"Price alerts",value:"4",detail:"For saved commodities"},{label:"Local advisories",value:"3",detail:"Pune district"}], actions:["Read briefing","Manage alerts","Save commodity"] },
  { slug:"smart-farm", name:"IoT & smart farm", eyebrow:"CONNECTED OPERATIONS", description:"Sensors, greenhouse automation, drones and equipment health in real time.", accent:"green", features:["Sensor dashboard","Drone missions","Drip automation","Moisture alerts","Smart greenhouse","Device registry"], metrics:[{label:"Online devices",value:"24/26",detail:"2 need attention"},{label:"Readings today",value:"38.4K",detail:"99.7% accepted"},{label:"Water saved",value:"18%",detail:"This cycle"}], actions:["Open telemetry","Register device","Create alert rule"] },
];

export const findSuperModule = (slug: string) => superModules.find(module => module.slug === slug);
