export type FieldType = "text" | "number" | "date" | "select" | "measurement";
export type FarmTemplate = { key: string; name: string; category: string; icon: string; subjects: string; outputs: string[]; fields: { key: string; label: string; type: FieldType; unit?: string }[]; activities: string[] };
export const farmTemplates: FarmTemplate[] = [
  { key:"cattle",name:"Cattle & oxen",category:"Livestock",icon:"Cow",subjects:"animals",outputs:["milk","calves","manure","draft work"],fields:[{key:"breed",label:"Breed",type:"text"},{key:"weight",label:"Weight",type:"measurement",unit:"kg"},{key:"lactation",label:"Lactation stage",type:"select"}],activities:["feeding","vaccination","deworming","breeding","weight check"] },
  { key:"small-ruminants",name:"Goats & sheep",category:"Livestock",icon:"Sheep",subjects:"animals",outputs:["milk","meat","wool","manure"],fields:[{key:"breed",label:"Breed",type:"text"},{key:"weight",label:"Weight",type:"measurement",unit:"kg"}],activities:["feeding","vaccination","breeding","hoof care"] },
  { key:"rabbit",name:"Rabbit farming",category:"Livestock",icon:"Rabbit",subjects:"animals",outputs:["kits","manure"],fields:[{key:"breed",label:"Breed",type:"text"},{key:"litter",label:"Litter number",type:"number"}],activities:["feeding","breeding","health check"] },
  { key:"poultry",name:"Hen, duck & turkey",category:"Poultry",icon:"Bird",subjects:"flocks",outputs:["eggs","birds","manure"],fields:[{key:"birdCount",label:"Bird count",type:"number"},{key:"layRate",label:"Lay rate",type:"measurement",unit:"%"}],activities:["feeding","vaccination","egg collection","incubation"] },
  { key:"apiary",name:"Beekeeping",category:"Apiculture",icon:"Hexagon",subjects:"colonies",outputs:["honey","wax","pollination"],fields:[{key:"hives",label:"Hive count",type:"number"},{key:"queenYear",label:"Queen year",type:"number"}],activities:["hive inspection","feeding","harvest","queen check"] },
  { key:"sericulture",name:"Silk farming",category:"Sericulture",icon:"Waves",subjects:"batches",outputs:["cocoons","silk"],fields:[{key:"worms",label:"Larvae count",type:"number"},{key:"stage",label:"Lifecycle stage",type:"select"}],activities:["feeding","bed cleaning","mounting","harvest"] },
  { key:"field-crops",name:"Sugarcane, corn & seeds",category:"Crops",icon:"Wheat",subjects:"crop batches",outputs:["cane","grain","seed"],fields:[{key:"variety",label:"Variety",type:"text"},{key:"area",label:"Cultivated area",type:"measurement",unit:"acre"}],activities:["sowing","irrigation","fertilising","scouting","harvest"] },
  { key:"horticulture",name:"Coconut, flowers & orchards",category:"Horticulture",icon:"Flower2",subjects:"blocks",outputs:["coconuts","flowers","fruit"],fields:[{key:"variety",label:"Variety",type:"text"},{key:"plantCount",label:"Plant count",type:"number"}],activities:["irrigation","pruning","pollination","harvest"] },
  { key:"protected",name:"Greens & greenhouse",category:"Protected cultivation",icon:"Sprout",subjects:"growing zones",outputs:["leafy greens","vegetables","herbs"],fields:[{key:"system",label:"Growing system",type:"select"},{key:"area",label:"Growing area",type:"measurement",unit:"m²"}],activities:["transplanting","nutrient dosing","climate check","harvest"] },
  { key:"vermiculture",name:"Vermiculture",category:"Circular farming",icon:"Recycle",subjects:"beds",outputs:["vermicompost","vermiwash"],fields:[{key:"bedCount",label:"Bed count",type:"number"},{key:"moisture",label:"Moisture",type:"measurement",unit:"%"}],activities:["feeding","moisture check","turning","harvest"] },
  { key:"aquaculture",name:"Fish farming",category:"Aquaculture",icon:"Fish",subjects:"ponds",outputs:["fish","fingerlings"],fields:[{key:"species",label:"Species",type:"text"},{key:"stock",label:"Stock count",type:"number"},{key:"do",label:"Dissolved oxygen",type:"measurement",unit:"mg/L"}],activities:["feeding","water test","sampling","harvest"] },
  { key:"dairy",name:"Milk & dairy products",category:"Dairy",icon:"Milk",subjects:"collection lots",outputs:["milk","curd","paneer","ghee","butter","cheese"],fields:[{key:"volume",label:"Milk volume",type:"measurement",unit:"L"},{key:"fat",label:"Fat",type:"measurement",unit:"%"},{key:"snf",label:"SNF",type:"measurement",unit:"%"}],activities:["milking","quality test","chilling","processing","dispatch"] }
];
export function templateByKey(key: string) { return farmTemplates.find(template => template.key === key); }
