import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { isOriginAllowed, requireSession } from "@/lib/auth";
import { managedFarms } from "@/lib/farms";
import { can, type Role } from "@/lib/roles";
const schema = z.object({ name: z.string().trim().min(2).max(80), type: z.enum(["Hydroponics", "Coconut", "Goat dairy", "Poultry", "Mixed farm", "Bee apiary", "Flower farm", "Leafy greens", "Greenhouse", "Orchard", "Aquaculture"]), location: z.string().trim().min(2).max(100), area: z.string().trim().min(1).max(30) });
const valid = (r: Request) => { const token = r.headers.get("x-csrf-token"); return isOriginAllowed(r) && token === r.headers.get("cookie")?.match(/agroos_csrf=([^;]+)/)?.[1]; };
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await requireSession(); if (!can(user.role as Role, "farm:write") || !valid(request)) return apiError(403, "FORBIDDEN", "This update was not allowed."); const body = schema.safeParse(await request.json()); if (!body.success) return apiError(400, "VALIDATION_ERROR", "Invalid farm data."); const { id } = await params; const farm = managedFarms.find(f => f.id === id); if (!farm) return apiError(404, "NOT_FOUND", "Farm not found."); Object.assign(farm, body.data, { updatedAt: "just now" }); return NextResponse.json({ farm }); } catch { return apiError(401, "UNAUTHENTICATED", "Sign in is required."); } }
export async function DELETE(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await requireSession(); if (!can(user.role as Role, "farm:delete") || !valid(request)) return apiError(403, "FORBIDDEN", "Only organisation owners can remove farms."); const id = (await params).id; const index = managedFarms.findIndex(f => f.id === id); if (index < 0) return apiError(404, "NOT_FOUND", "Farm not found."); managedFarms.splice(index, 1); return new NextResponse(null, { status: 204 }); } catch { return apiError(401, "UNAUTHENTICATED", "Sign in is required."); } }
