"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { BarChart3, Bell, Bot, Building2, ChevronDown, LayoutDashboard, Leaf, Search, Settings, ShieldCheck, ShoppingBag, Sprout, Warehouse } from "lucide-react";
type NavItem = { href: string; label: string; icon: React.ComponentType<{ size?: number }> ; roles?: string[] };
const navigation: { label: string; items: NavItem[] }[] = [
  { label: "Workspace", items: [{href:"/dashboard",label:"Overview",icon:LayoutDashboard},{href:"/dashboard/farming",label:"Farming engine",icon:Sprout,roles:["OWNER","MANAGER","FARM_MANAGER","SPECIALIST","OPERATOR","VIEWER"]},{href:"/dashboard/farms",label:"Farm registry",icon:Building2,roles:["OWNER","MANAGER","FARM_MANAGER","OPERATOR","VIEWER"]},{href:"/dashboard/intelligence",label:"Intelligence",icon:Bot}] },
  { label: "Business", items: [{href:"/dashboard/marketplace",label:"Marketplace",icon:ShoppingBag},{href:"/dashboard/cold-chain",label:"Cold chain",icon:Warehouse},{href:"/dashboard/analytics",label:"Analytics",icon:BarChart3,roles:["OWNER","MANAGER","FARM_MANAGER","SPECIALIST","ACCOUNTANT","VIEWER"]}] },
  { label: "Manage", items: [{href:"/dashboard/admin",label:"Administration",icon:ShieldCheck,roles:["PLATFORM_ADMIN","SUPPORT_AGENT","OWNER"]},{href:"/dashboard/settings",label:"Settings",icon:Settings}] }
];
export function AppShell({ children, user }: { children: React.ReactNode; user: { name: string; email: string; role: string } }) {
  const pathname = usePathname(); const items = navigation.map(group => ({ ...group, items: group.items.filter(item => !item.roles || item.roles.includes(user.role)) })).filter(group => group.items.length);
  return <div className="app-shell-v2"><aside className="sidebar-v2"><Link className="brand-v2" href="/dashboard"><span className="brand-mark"><Leaf size={17}/></span><span>AgroOS<small>Connected agriculture</small></span></Link><button className="workspace-switcher"><span className="workspace-icon">GV</span><span><strong>Green Valley</strong><small>Farm workspace</small></span><ChevronDown size={14}/></button><nav aria-label="Primary navigation">{items.map(group => <div className="nav-group" key={group.label}><p>{group.label}</p>{group.items.map(item => { const Icon=item.icon; const active=pathname===item.href || (item.href!=="/dashboard" && pathname.startsWith(item.href)); return <Link aria-current={active?"page":undefined} className={active?"active":""} key={item.href} href={item.href}><Icon size={17}/><span>{item.label}</span></Link>; })}</div>)}</nav><div className="account-v2"><span className="avatar">{user.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><div><strong>{user.name}</strong><small>{user.role.replaceAll("_"," ").toLowerCase()}</small></div><form action="/api/auth/logout" method="post"><button type="submit" aria-label="Sign out">↗</button></form></div></aside><div className="workspace-main"><header className="topbar"><label className="command-search"><Search size={16}/><input aria-label="Search AgroOS" placeholder="Search farms, animals, orders…"/><kbd>⌘ K</kbd></label><div className="top-actions"><span className="environment-badge">Live workspace</span><button className="icon-button" aria-label="Notifications"><Bell size={18}/><i/></button></div></header><main className="content-v2">{children}</main></div></div>;
}
