"use client";
import { FormEvent, useState, useTransition } from "react";
import type { ManagedFarm, FarmType } from "@/lib/farms";
const types: FarmType[] = ["Hydroponics", "Coconut", "Goat dairy", "Poultry", "Mixed farm"];
const csrf = () => document.cookie.split("; ").find(v => v.startsWith("agroos_csrf="))?.split("=")[1] ?? "";
export function FarmRegistry({ initialFarms, canManage }: { initialFarms: ManagedFarm[]; canManage: boolean }) {
  const [farms, setFarms] = useState(initialFarms); const [editing, setEditing] = useState<ManagedFarm | null>(null); const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  const save = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const item = { name: String(form.get("name")), type: String(form.get("type")) as FarmType, location: String(form.get("location")), area: String(form.get("area")) };
    startTransition(async () => { const method = editing ? "PATCH" : "POST"; const url = editing ? `/api/farms/${editing.id}` : "/api/farms"; const res = await fetch(url, { method, headers: { "Content-Type": "application/json", "X-CSRF-Token": csrf() }, body: JSON.stringify(item) }); if (!res.ok) { setMessage("Could not save the farm. Please try again."); return; } const { farm } = await res.json(); setFarms(items => editing ? items.map(old => old.id === farm.id ? farm : old) : [farm, ...items]); setOpen(false); setEditing(null); setMessage(`${farm.name} saved.`); }); };
  const remove = (id: string) => startTransition(async () => { if (!confirm("Remove this farm from the workspace?")) return; const res = await fetch(`/api/farms/${id}`, { method: "DELETE", headers: { "X-CSRF-Token": csrf() } }); if (res.ok) { setFarms(items => items.filter(farm => farm.id !== id)); setMessage("Farm removed."); } });
  return <><div className="section-heading"><div><p className="eyebrow">FARM REGISTRY</p><h1>All farming operations</h1><p className="muted">Manage crop, livestock, dairy, coconut, poultry, and mixed-farm locations.</p></div>{canManage && <button className="button primary" onClick={() => { setEditing(null); setOpen(true); }}>Add farm</button>}</div><p className="sr-only" aria-live="polite">{message}</p><section className="farm-cards">{farms.map(farm => <article className="panel farm-card" key={farm.id}><span className="farm-symbol">{farm.type === "Coconut" ? "◉" : farm.type === "Goat dairy" ? "◌" : farm.type === "Poultry" ? "◈" : "✦"}</span><div><p className="eyebrow">{farm.type}</p><h2>{farm.name}</h2><p>{farm.location} · {farm.area}</p></div><div className="farm-footer"><span className="healthy-text">{farm.status}</span><small>Updated {farm.updatedAt}</small>{canManage && <span><button className="inline-action" onClick={() => { setEditing(farm); setOpen(true); }}>Edit</button><button className="inline-action danger" disabled={pending} onClick={() => remove(farm.id)}>Remove</button></span>}</div></article>)}</section>{open && <div className="modal-backdrop" role="presentation"><form className="modal-card" onSubmit={save} aria-label={editing ? "Edit farm" : "Add farm"}><div className="section-heading"><div><p className="eyebrow">FARM REGISTRY</p><h2>{editing ? "Edit farm" : "Add a farm"}</h2></div><button type="button" className="text-button dark" onClick={() => setOpen(false)}>Close</button></div><label>Farm name<input name="name" defaultValue={editing?.name} required maxLength={80}/></label><label>Farm type<select name="type" defaultValue={editing?.type ?? "Mixed farm"}>{types.map(type => <option key={type}>{type}</option>)}</select></label><label>Location<input name="location" defaultValue={editing?.location} required maxLength={100}/></label><label>Area<input name="area" defaultValue={editing?.area} required maxLength={30}/></label><button className="button primary" disabled={pending} type="submit">{pending ? "Saving…" : "Save farm"}</button></form></div>}</>;
}
