import type { ReactNode } from "react";
import Link from "next/link";
export function MetricCard({label,value,detail,tone=""}:{label:string;value:string;detail:string;tone?:""|"healthy"|"warning"|"critical"}){return <article className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
export function StatusBadge({children,tone="healthy"}:{children:ReactNode;tone?:"healthy"|"warning"|"critical"|"neutral"}){return <span className={`ui-status ${tone}`}>{children}</span>}
export function ProgressRing({value,label}:{value:number;label:string}){return <div className="progress-ring" style={{"--progress":`${Math.max(0,Math.min(100,value))*3.6}deg`} as React.CSSProperties} role="img" aria-label={`${label}: ${value}%`}><div><strong>{value}%</strong><small>{label}</small></div></div>}
export function DataChart({values,labels,label}:{values:number[];labels?:string[];label:string}){const max=Math.max(...values,1);return <div className="data-chart" role="img" aria-label={label}>{values.map((value,index)=><span key={`${value}-${index}`} style={{height:`${Math.max(5,value/max*100)}%`}} title={`${labels?.[index]??index}: ${value}`}/>)}</div>}
export function AlertBanner({title,children,tone="warning"}:{title:string;children:ReactNode;tone?:"warning"|"critical"|"info"}){return <div className={`alert-banner ${tone}`} role="status"><strong>{title}</strong><span>{children}</span></div>}
export function ModuleCard({href,title,description,meta}:{href:string;title:string;description:string;meta:string}){return <Link className="ui-module-card" href={href}><span>{meta}</span><h3>{title}</h3><p>{description}</p><b>Open →</b></Link>}
export function WeatherWidget({temperature,rain,summary}:{temperature:string;rain:string;summary:string}){return <article className="weather-widget"><p className="eyebrow">HYPERLOCAL WEATHER</p><strong>{temperature}</strong><span>{summary}</span><small>{rain} chance of rain</small></article>}
export function NewsCard({title,source,summary}:{title:string;source:string;summary:string}){return <article className="panel news-card"><span className="ui-status neutral">{source}</span><h2>{title}</h2><p>{summary}</p><button className="inline-action">Read briefing →</button></article>}
export function ActivityFeed({items}:{items:{title:string;detail:string;time:string}[]}){return <div className="activity-feed">{items.map(item=><div key={`${item.title}-${item.time}`}><i/><p><strong>{item.title}</strong><small>{item.detail}</small></p><time>{item.time}</time></div>)}</div>}
